import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          'WelcomeTo': 'Welcome to  ',
          'Longevity': 'Longevity',
          'Hub': 'Hub',
          "WelcomeScreen1text":
              "The first fitness App Improve your fitness, practice mindfulness, or prepare for new adventures with a series of specially designed workouts and meditations.",
          'GeStarted': 'Get Started',
          'WhereverYouAre': 'Wherever You Are ',
          'Health': 'Health ',
          'is': 'Is',
          'NumberOne': 'Number One',
          'Workout': 'Workout ',
          'Categories': ' Categories',
          'BeginYour': 'Begin Your ',
          'Transformation': 'Transformation',
          'NewEra': 'New Era ',
          'of': 'of ',
          'Wellbeing': 'Wellbeing',
          'WelcomeScreen2text':
              'Find out exactly what diet & training will work specifically for you.',
          "WelcomeScreen3text":
              'Workout categories will help you gain strength, get in better shape and embrace  a healthy lifestyle.',
          'WelcomeScreen4text':
              ' Our AI analyzes your health data to suggest personalized meal plans with recipes.',
          'WelcomeScreen5text':
              'Wellness at Your Fingertips, Deep Insights, Better Health, Nutrition Tailored for You, Move Smarter, Live Better, Ready to Begin?',
          'skip': 'skip',
          'WelcomeBack': 'Welcome Back',
          'ForgotPassword?': 'Forgot Password?',
          'ForgotPassword': 'Forgot Password',
          "SignIn": "Sign In",
          "SignInWith": "Sign in with",
          "signup": " Sign Up",
          'DontHaveAnAccount?': 'Don`t have an account?',
          'ForgetPasswordScreenText':
              'It happen, kindly enter the email associated with your account.',
          "pleaseenteremail": "Please enter email",
          "emailaddress": "Email Address",
          'submit': 'Submit',
          'cancel': 'Cancel',
          'NeedHelp?VisitOur': 'Need help? Visit our ',
          'HelpCenter': 'help center',
          'Email': 'Email',
          'EnterEmail': 'Enter Email',
          'EnterPassword': 'Enter Password',
          'Password': "Password",

          // Otp Screen
          "enterotp": "Enter OTP",
          "thankyou": "Thank you!",
          "otpsendtoyouremail": "An OTP has been sent to your email address",
          "expiresin": "Expires in",
          "resend": "Re-send",
          "otpfailed": "OTP verification failed",

          //createNewPasswordScreen
          "createnewpass": "Create New Password",
          "kindlyenteruniquePass": "Kindly enter a unique Password",
          "enterPass": "Enter Password",
          "passMustbe6characterlong":
              "Password must be at least 6 characters long",
          "mustContainUppercaseletter":
              "Password must contain at least one uppercase letter",
          "mustcontainOneNumber": "Password must contain at least one number",
          "mustcontainSpecialChar":
              "Password must contain at least one special character",
          "newPass": "New Password",
          "confirmnewPass": "Confirm New Password",
          "passresetFailed": "Password reset failed",

          //passsuccessScreen
          "youwillberedirectedin5":
              "You will be redirected to the login page in 5 seconds...",
          "click": "Click ",
          "Here": "here ",
          "ifYounotredirect":
              "if you are not redirected \n                      automatically",
          //SignupScreen
          "enteruserName": "Enter Username",
          "shouldOnlycontainAlphabets":
              "Username should only contain alphabets",
          "name": "Name",
          "enterPhone": "Enter phone",
          "shouldonlyContainDigits": "Phone number should only contain digits",
          "phone": "Phone",
          "enterEmail": "Enter Email",
          "invalidEmailFormat": "Invalid Email Format",
          "email": "Email",
          "password": "Password",
          "enterconfirmPass": "Enter Confirm Password",
          "confirmPass": "Confirm Password",
          "orRegisterWith": "Or Register With",
          "alreadyhaveanAccount": "Already have an account?",
          "login": " Login!",

          //stepsScreen
          //genderScreen
          "step1of7": "Step 1 of 7",
          "tellusaboutyourself": "Tell us about yourself!",
          "toGiveYoubetterexperiance":
              "To give you a better experience we need to know\nyour gender.",
          "male": "Male   ",
          "female": "Female",
          "next": "Next",
          //ageScreen
          "step2of7": "Step 2 of 7",
          "howoldareyou": "How old are you ?",
          "thishelpuscreateplan":
              "This helps us create your personalized plan.",
          "jan": "Jan",
          "feb": 'Feb',
          "mar": 'Mar',
          "apr": 'Apr',
          "may": 'May',
          "jun": 'Jun',
          "jul": 'Jul',
          "aug": 'Aug',
          "sep": 'Sep',
          "oct": 'Oct',
          "nov": 'Nov',
          "dec": 'Dec',
          //heightScreen
          "step3of7": "Step 3 of 7",
          "selectHeight": "Select Height",
          "thishelpcreateyourplan":
              "This helps us create your personalized plan.",
          "feet": "Feet",
          //weightScreen
          "step4to7": "Step 4 of 7",
          "whatisyourweight": "What is your weight?",
          "youcanchangelater": "You can always change this later.",
          //physicalActivityLevel
          "step5of7": "Step 5 of 7",
          "yourphysicalActivitylevel": "Your regular physical activity level ?",
          //activitylevelScreen
          "step6of7": "Step 6 of 7",
          "chooseactivity": "Choose activities \n     that interest.",
          "noactivityavailable": "No activities available.",
          "pleaseselectoneactivity":
              "Please select at least one activity to proceed.",
          "warning": "Warning!",
          "ok": "OK",
          //selectdiseaseScreen
          "step7of7": "Step 7 of 7",
          "selectDisease": "Select Disease",
          "search": "Search",
          //welcomeScreen
          "welcometolongevity": "Welcome\nLongevity Hub",
          "workoutsforeveryone": "Workouts for Everyone",
          "elevenDifferentTypesfromHiit":
              "Eleven different types from HIIT to Yoga",
          "guidedMeditation": "Guided Meditations",
          "paracticemindfullnesin":
              "Practice mindfulness in as little as 5 minutes",
          "programandmore": "Programs, Collections, and More",
          "welcomeText":
              "When you explore the Longevity Hub service prior to subscribing, Longevity Hub may use your browsing activity in the Longevity Hub tab to improve the service. Once you subscribe, your browsing and workout data are associated with a random identifier. Your account, subscription status, and workouts may be used to send you notifications.",
          "seehowmanage": "See how your data is managed.",
          "agree": "Agree",

          //menuScreen
          "user": "User",
          "healthInsights": "Health Insights",
          "healthatoz": "Health A-Z",
          "wellness": "Wellness",
          "subscription": "Subscription",
          "biometric": "Biometric",
          "languages": "Languages",
          "myorders": "My Orders",
          "privecypolicy": "Privacy Policy",
          "terms&condition": "Terms & Conditions",
          "faqs": "FAQS",
          "deletaccount": "Delete Account",
          "logout": "Logout",

          "confirmaccountdeletion": "Confirm Account Deletion",
          "areyousuredeleteaccount":
              "Are you sure you want to delete your account?",
          "Cancel": " Cancel ",
          "confirm": "Confirm",
          "termsandcondition": "Terms and Conditions",
          "faq's": "FAQ's",
          "comingsoon": "Coming Soon",
          "selectLanguage": "Select Languauge",
          //subscription
          "validforlifetime": "Valid for Lifetime",
          "until": "Until",
          "basic": "Basic",
          "yearsubscription": "Year Subscription",
          "monthsubsricption": "Month Subscription",
          "daysubscription": "Day Subscription",
          "errorfetchingdata": "Error fetching data:",
          "subscriptionplan": "Subscription Plan",
          "unlockyourfullpotiential":
              "Unlock Your Full Potential with Our Subscription Plans",
          "nosubscriptionplan": "No subscription plans available.",
          "subscribe": "Subscribe",
          "nofeaturesfound": "No Features Found",
          "unsubscribe": "UnSubscribe",
          //wellness
          "discoverwellness": "Discover Wellness",
          "becomeyourbestself":
              "Become your best self by embracing natural beauty, \nnutritious eating, an active lifestyle, and strong relationships.",
          "healthaz": "Health A-Z",
          "becomeyourlifestyle":
              "Become your best self through natural beauty, healthy nutrition, an active lifestyle,   and meaningful relationships.",
          "catagories": "Categories",
          "viewMore": "View More",

          //HealthInsights
          "todayworkout": "Today Workout",
          "heartRate": "Heart Rate",
          "steps": "Steps",
          "water": "Water",
          "glasses": "Glasses",
          "sleeping": "Sleeping",
          "hours": "hours",
          "earn": "Earn",
          "badges": "Badges",
          "connectwearable": "Connect Wearable",
          "setworkoutgoal": "Set Workout Goal",
          "activitystats": "Activity Statistic",
          "setGoal": "Set Goal",
          "calories": "Calories",
          "KCal": "kcal",
          "timespend": "Time Spend",
          "sun": "SUN",
          "mon": "MON",
          "tue": "TUE",
          "wed": "WED",
          "thu": "THU",
          "fri": "FRI",
          "sat": "SAT",
          "summary": "Summary",
          "overallprogress": "Overall Progress",
          "mealGuide": "Meal Guide",
          "breakfast": "Break Fast",
          "lunch": "Lunch",
          "dinner": "Dinner",
          "myprogram": "My Program",
          "overheadextension": "Overhead Bar Extensions",
          "minutesleft": "Minutes Left",
          "workoutdetail": "Workout Detail",
          "seeall": "See all",
          "day": "Day",
          "selectany5": "Select Any 5 Exercises",
          "legpressMachine": "Leg Press Machine",
          "minutes": "Minutes",
          "Each": "each",
          "workout": "Workout",
          "daily": "Daily",
          "weekly": "Weekly",
          "monthly": "Monthly",
          "Minutes": "mins",
          "exercise": "Exercise",
          "your": "Your",
          "KCAL": "Kcal",
          "bodytemp": "Body\nTemperature",
          "normal": "Normal",
          "editWorkout": "Edit Workout",
          "finish": "Finish",
          "SUN": "Sun",
          "MON": "Mon",
          "TUE": "Tue",
          "WED": "Wed",
          "THU": "Thu",
          "FRI": "Fri",
          "SAT": "Sat",
          "caloriesburnt": "Calories burnt",
          "Caloriesleft": "Calories left",
          "1stweek": "1st Week",
          "workoutreport": "Workout Report",
          "average": "Average:",
          "2ndweek": "2nd Week",
          "3rdweek": "3rd Week",
          "4thweek": "4th Week",
          "5thweek": "5th Week",
          "history": "History",
          "heartbpms": "Heart's bpm",
          "bpmrange": "Bpm Range",
          "resting": "Resting",
          "hightoday": "High Today",
          "lowtoday": "Low Today",
          "bloodpressure": "Blood Pressure",
          "values": 'Values',
          "condition": "Condition",
          "date/time": "Date/Time",
          "High": "high",
          "setmovegoal": "Set Move Goal",
          "yourdailymovegoal": "Your Daily\nMove Goal",
          "setactivegoal":
              "Set a goal based on how active you are, or how\n               active you’d like to be, each day.",
          "kilocalperday": "KILOCALORIES/DAY",
          "stepscount": "Steps Count",
          "walking": "WALKING",
          "distance": "Distance",
          "running": "RUNNING",
          "editgoal": "Edit Goal",
          "totalsteps": "Total Steps",
          "avgsteps": "Avg Steps",
          "stepsreport": "Steps Report",
          "today": "Today",
          "hi": "Hi",
          "oop": "Oop's!",
          "hasnotachieve": "has not achive \n your goal today",
          "successisnotfinal":
              "Success is not final, failure is not \nfatal: it is the courage to continue \nthat count.",
          "tryagain": "Try Again",
          "pleaseselectactivity": "Please select an activity first!",
          "inprogress": "In Progress!",
          "almostdone": "Almost Done!",
          "completed": "Completed!",
          "goodjob": "Good Job!",
          "yourdailytask": "Your Daily Tasks",
          "+addactivity": "+ Add Activity",
          "glassofwater": " Glass of Water",
          "glassesofWater": " Glasses of Water",
          "noactivityfound": "No activity found add Activity first",
          "glass": "Glass",
          "totalIntake": "Total Intake",
          "pending": "Pending",
          "healthySleep": "Healthy Sleep",
          "sleeptime": "Sleep Time",
          "thisweek": "This Week",
          "Hours": "hours",
          "perday": "per day",
          "quality": "Quality",
          "lastsleepinfo": "Last sleep information",
          "timeinsleep": "Time in sleep",
          "wakeuptime": "Wake up time",
          "wenttobed": "Went to bed",
          "fellasleep": "Fell asleep",
          "bedtime": "Bed Time",
          "alarm": "Alarm",
          "setbedtime": "Set Bed Time",
          "bedTime": "Bed Time",
          "wake_uptime": "Wake-up Time",
          "setAlarm": "Set Alarm",
          "time": "Time",
          "rewards": "Rewards",
          "Sleeping": "S L E E P I N G",
          "Rewards": "R E W A R D S",
          "Steps": "S T E P S",
          "WOrkout": "W O R K O U T",
          "waterIntake": "W A T E R    I N    T A K I N G",
          "addcategory": "Add Category",
          "selectcategory": "Select Category",
          "pleaseselectcategory": "Please select a category",
          "pleaseenterquantityofglass": "Please enter quantity of glasses",
          "quantityofGlass": "Quantity of Glasses",
          "save": "Save",
          //Profile
          "profile": "Profile",
          "basicmember": "Basic member",
          "weight": "Weight",
          "height": "Height",
          "year": "Year",
          "age": "Age",
          "category": "Category",
          "justforyou": "Just for you",
          "befree": "Be Free",
          "mInutes": "min",
          //EditProfile
          "editprofile": "Edit Profile",
          "pleaseenterusername": "Please Enter Username",
          "fullname": "Full Name",
          "pleaseenterphone": "Please Enter phone",
          "phoneshouldcontaindigits": "Phone number should only contain digits",
          "pleaseenteraddress": "Please Enter Email Address",
          "emailAddress": "Email Address",
          "pleaseenterweight": "Please Enter weight",
          "pleaseenterheight": "Please Enter Height",
          "gender": "Gender",
          "disease": "Diseases",
          "activitylevel": "Activity Level",
          "update": "Update",
          "choosephoto": "Choose Profile Photo",
          "camera": "Camera",
          "gallery": "Gallery",
          "selectdiseases": "Select Diseases",
          //Notification
          "yesterday": "Yesterday",
          "previous": "Previous",
          "nonotificationyet": "No notifications yet",
          "notificationactivity": "Notifications about your activity will",
          "shopuphere": "show up here.",
          "notification": "Notification",
          //home

          "fityoungmandoing": "  Fit Young man Doing\nBattle Stretch  Training",
          "startexercise": "Start Exercise",
          "whatareyoulookingfor": "What are you looking for ?",
          "improvelife": "Improve your\nlifestyle",
          "gym": "Gym",
          "choosegym": "Choosing the\nRight Gym\nfor You",
          "shopOnline": "Shop Online",
          "gymandmore": "Gym Gadgets, Nutrition,\nSupplements, and More!",
          "trackheart": "Track Heart Rate,\nWorkouts, and More!",
          "nutrition": "Nutrition",
          "balancediet": "The Importance of a Balanced Diet",
          "community": "Community",
          "center": "Center",
          "schedule": "Schedule",
          "home": "Home",

          // SelectGymScreen
          "SelectGym": "Select Gym",
          'SelectGymScreenText':
              "Get Your Fitness Back on Track with\nOur Gym Members",
          'NoGymAvailable': "No gyms available.",
          'SubscribeToPremium': 'SUBSCRIBE TO PREMIUM',
          'SelectGymScreenText2':
              'Enjoy unlimited access to our premium content',
          "selectgym": "SELECT GYM",
          //TrainersScreen
          "FitnessTrainer": "Fitness Trainer",
          "NoTrainersAvailableForThisGym.":
              "No trainers available for this gym.",
          "years": "years",
          "Online": "Online",
          "activeClients": "Active Clients",
          "HaveMadeAnAppointment": "have made an appointment",
          "beginTraining": "Begin Training",
          // TrainersInfoScreen
          'HighIntensityTraining': "High Intensity Training",
          "Reviews": "Reviews",
          "BeginTraining": "Begin Training",
          "ReadAllReviews": "Read all reviews",
          "NoReviewsAvailable": "No Reviews Available",
          "Experience": "Experience",
          "Completed": "Completed",
          "ActiveClients": "Active Clients",
          // GymExerciseScreen
          "NoVideoFoundAgainstthisCategory":
              "No Video Found Against This Category",
          "Exercise": "Exercise",
          "16ActiveClients": "16 Active Clients",
          // "HaveMadeAnAppointment": "have made an appointment",
          "AvailableTimings": "Available Timings",
          "09:00 am": "09:00 am",
          "05:00 pm": "05:00 pm",
          //TrainerAppointmentScreen
          "Appointment": "Appointment",
          "SelectDate": "Select Date",
          "SelectTime": "Select Time",
          "Appointment Notes": "Appointment Notes",
          "PayOnline": "Pay Online",
          // TrainerReviewsScreen
          "Ratings": "Ratings",
          "WriteAReview": "Write a Review",
          "review(optional)": "Review (Optional)",
          "send": "Send",
          "rating": "Rating",
          // WorkOutDetailScreen
          "MyExercises": "My Exercises",
          "ExerciseDescriptionGoesHere.": "Exercise description goes here.",
          "Done": "Done",
          "FailedToLoadVideo": "Failed to load video",
          "pleasecompleteprevious": "Please complete the previous reps first",

          //changepassword
          "changePass": "Change Password",
          "enteroldPass": "Enter old Password",
          "passresetfailed": "Password reset failed",

          //custompopup
          "attention": "Attention!",
          "updatepackage": "Update Package",

          //community
          "createCommunity": "Create Community",
          "connectwithcommunity": "Connect with the Community",
          "selectyourcommunity": "Select Your Community",
          "communitypermission": "Community Permissions",
          "approvenewmember": "Approve New Members",
          "sendmessage&activity": "Send Messages & Activities",
          "addothermembers": "Add other Members",
          "addmembers": "Add Members",
          "searchid": "Search ID",
          "joingroup": "Join Group",
          "chat": "Chat",
          "members": "Members",
          "searchanyrecipe": "Search any recipes",
          "upcomingevents": "upcoming events",
          //shoponline
          "searchhere": "Search here",
          "color": "Colour",
          "addtocart": "Add to Cart",
          "mycart": "My Cart",
          "myOrders": "My Orders",
          "itemTotal": "Item Total",
          "selectbadge": "Select Badge",
          "discount": "Discount",
          "deliveryfee": "Delivery Fee",
          "grandtotal": "Grand Total",
          "ordernow": "Order Now",
          "orderId": "Order ID:",
          "orderDate": "Order Date & Time:",
          "qty": "QTY:",
          "delivered": "Delivered",
          "viewDetails": "View Details",
          "reorder": "Reorder",
          "placed": "Placed",
          "cancelled": "Cancelled",
          "orderdetails": "Order Details",
          "cancelOrder": "Cancel Order",
          "return": "Return",
          "deliveryAddress": "Delivery Address",
          "orderSummary": "Order Summary",
          "viewInvoice": "View Invoice",
          "favourite": "Favourite",
          "Addtocart": "add to card",
          "shippingaddress": "Shipping Address",
          "address": "Address",
          "Summary": "Summary",
          "payment": "Payment",
          "addnewaddress": "+ Add New Address",
          "paynow": "Pay Now",
          "yourpaymentdone": "Your payment done\n        successfully.",
          "thankyouforshopping": "Thank you for shopping with us",
          "seeorderDetails": "See Order Details",
          "continueshopping": "Continue Shopping",

          //Schedule
          "myAppointments": "My Appointments",
          "upcoming": "Upcoming",
          "cOmpleted": "Completed",
          "bookingid": "Booking ID:",
          "booked": "Booked",
          "onlineConsultation": "Online Consultation",
          "reschedule": "Reschedule",
          "bookanAppointment": "Book an Appointment",
          "selectExpert": "Select Expert",
          "online": "Online",
          "havemadeappointment": "have made an appointment",
          "availabletimings": "Available Timings",
          "bookAppointment": "Book Appointment",
          "bookNow": "Book Now",
          "selectDate": "Select Date",
          "selectTime": "Select Time",
          "appointmentNotes": "Appointment Notes",
          "experiance": "Experiance",
          "readallReviews": "Read all reviews",
          "reviews": "Reviews",
          "ratings": "Ratings",
          "writeareview": "Write a Review",

          "yoursessionwith": "Your session with",
          "iscompleted": "is complete! 🎉",
          "welovetohere": "We would love to hear from you",
          "feedback": "Feedback",
          "writeyourfeedback": "Write your feedback here",
          "skip&godashboard": "Skip & Go to Dashboard",
        },
        "ar_SA": {
          'WelcomeTo': 'مرحبًا بكم في',
          'Longevity': "Longevity",
          'Hub': "Hub",
          "WelcomeScreen1text":
              "أول تطبيق للياقة البدنية. حسن لياقتك البدنية، مارس التأمل، أو استعد للمغامرات الجديدة مع مجموعة من التدريبات والتأملات المصممة خصيصًا",
          'GeStarted': 'ابدأ الآن',
          'WhereverYouAre': 'أينما كنت',
          'Health': 'الصحة',
          'is': 'هي',
          'NumberOne': 'الأولى',
          'Workout': 'التدريب',
          'Categories': 'الفئات',
          'BeginYour': 'ابدأ',
          'Transformation': 'تحولك',
          'NewEra': 'عصر جديد',
          'of': 'من',
          'Wellbeing': 'الرفاهية',
          'WelcomeScreen2text':
              'اكتشف بالضبط النظام الغذائي والتدريبات التي تناسبك',
          "WelcomeScreen3text":
              'ستساعدك فئات التمرين على اكتساب القوة، وتحسين لياقتك، واحتضان أسلوب حياة صحي',
          'WelcomeScreen4text':
              'يحلل الذكاء الاصطناعي بيانات صحتك لاقتراح خطط وجبات مخصصة مع وصفات',
          'WelcomeScreen5text':
              'العافية في متناول يدك، رؤى عميقة، صحة أفضل، تغذية مخصصة لك، تحرك بذكاء، عِش حياة أفضل. هل أنت مستعد للبدء؟',
          'skip': 'تخطى',
          'WelcomeBack': 'مرحبًا بعودتك',
          'ForgotPassword?': 'هل نسيت كلمة المرور؟',
          'ForgotPassword': 'نسيت كلمة المرور',
          "SignIn": "تسجيل الدخول",
          "SignInWith": "تسجيل الدخول باستخدام",
          "signup": "تسجيل",
          'DontHaveAnAccount?': 'ليس لديك حساب؟',
          'ForgetPasswordScreenText':
              'يحدث ذلك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك.',
          "pleaseenteremail": "يرجى إدخال البريد الإلكتروني",
          "emailaddress": "عنوان البريد الإلكتروني",
          'submit': 'إرسال',
          'cancel': 'إلغاء',
          'NeedHelp?VisitOur': 'تحتاج إلى مساعدة؟ تفضل بزيارة',
          'HelpCenter': 'مركز المساعدة',
          'Email': 'البريد الإلكتروني',
          'EnterEmail': 'أدخل البريد الإلكتروني',
          'EnterPassword': 'أدخل كلمة المرور',
          'Password': "كلمة المرور",

          // Otp Screen
          "enterotp": "أدخل رمز التحقق",
          "thankyou": "شكرًا لك!",
          "otpsendtoyouremail": "تم إرسال رمز التحقق إلى بريدك الإلكتروني",
          "expiresin": "ينتهي في",
          "resend": "إعادة إرسال",
          "otpfailed": "فشل التحقق من الرمز",

          //createNewPasswordScreen
          "createnewpass": "إنشاء كلمة مرور جديدة",
          "kindlyenteruniquePass": "يرجى إدخال كلمة مرور فريدة",
          "enterPass": "أدخل كلمة المرور",
          "passMustbe6characterlong":
              "يجب أن تكون كلمة المرور على الأقل 6 أحرف",
          "mustContainUppercaseletter":
              "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
          "mustcontainOneNumber":
              "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
          "mustcontainSpecialChar":
              "يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل",
          "newPass": "كلمة مرور جديدة",
          "confirmnewPass": "تأكيد كلمة المرور الجديدة",
          "passresetFailed": "فشل إعادة تعيين كلمة المرور",

          //passsuccessScreen
          "youwillberedirectedin5":
              "سيتم تحويلك إلى صفحة تسجيل الدخول في غضون 5 ثوانٍ...",
          "click": "انقر",
          "Here": "هنا",
          "ifYounotredirect":
              "إذا لم يتم تحويلك تلقائيًا \n                      انقر هنا",
          //SignupScreen
          "enteruserName": "أدخل اسم المستخدم",
          "shouldOnlycontainAlphabets":
              "يجب أن يحتوي اسم المستخدم على الحروف فقط",
          "name": "الاسم",
          "enterPhone": "أدخل الهاتف",
          "shouldonlyContainDigits": "يجب أن يحتوي رقم الهاتف على أرقام فقط",
          "phone": "الهاتف",
          "enterEmail": "أدخل البريد الإلكتروني",
          "invalidEmailFormat": "صيغة بريد إلكتروني غير صالحة",
          "email": "البريد الإلكتروني",
          "password": "كلمة المرور",
          "enterconfirmPass": "أدخل تأكيد كلمة المرور",
          "confirmPass": "تأكيد كلمة المرور",
          "orRegisterWith": "أو سجل باستخدام",
          "alreadyhaveanAccount": "هل لديك حساب بالفعل؟",
          "login": " تسجيل الدخول!",

          //stepsScreen
          //genderScreen
          "step1of7": "الخطوة 1 من 7",
          "tellusaboutyourself": "أخبرنا عن نفسك!",
          "toGiveYoubetterexperiance":
              "لمنحك تجربة أفضل، نحتاج إلى معرفة \n جنسك",
          "male": "ذكر",
          "female": "أنثى",
          "next": "التالي",
          //ageScreen
          "step2of7": "الخطوة 2 من 7",
          "howoldareyou": "كم عمرك؟",
          "thishelpuscreateplan": "هذا يساعدنا في إنشاء خطتك الشخصية",
          "jan": "يناير",
          "feb": 'فبراير',
          "mar": 'مارس',
          "apr": 'أبريل',
          "may": 'مايو',
          "jun": 'يونيو',
          "jul": 'يوليو',
          "aug": 'أغسطس',
          "sep": 'سبتمبر',
          "oct": 'أكتوبر',
          "nov": 'نوفمبر',
          "dec": 'ديسمبر',
          //heightScreen
          "step3of7": "الخطوة 3 من 7",
          "selectHeight": "اختر الطول",
          "thishelpcreateyourplan": "هذا يساعدنا في إنشاء خطتك الشخصية",
          "feet": "قدم",
          //weightScreen
          "step4to7": "الخطوة 4 من 7",
          "whatisyourweight": "ما هو وزنك؟",
          "youcanchangelater": "يمكنك دائمًا تغييره لاحقًا",
          //physicalActivityLevel
          "step5of7": "الخطوة 5 من 7",
          "yourphysicalActivitylevel": "ما هو مستوى نشاطك البدني؟",
          //activitylevelScreen
          "step6of7": "الخطوة 6 من 7",
          "chooseactivity": "اختر الأنشطة \n     التي تهمك",
          "noactivityavailable": "لا توجد أنشطة متاحة",
          "pleaseselectoneactivity":
              "يرجى اختيار نشاط واحد على الأقل للمتابعة.",
          "warning": "تحذير!",
          "ok": "موافق",
          //selectdiseaseScreen
          "step7of7": "الخطوة 7 من 7",
          "selectDisease": "اختر المرض",
          "search": "بحث",
          //welcomeScreen
          "welcometolongevity": "مرحبًا بكم\n Longevity Hub",
          "workoutsforeveryone": "تدريبات للجميع",
          "elevenDifferentTypesfromHiit":
              "أحد عشر نوعًا مختلفًا من HIIT إلى اليوغا",
          "guidedMeditation": "تأملات موجهة",
          "paracticemindfullnesin": "مارس اليقظة في غضون 5 دقائق فقط",
          "programandmore": "برامج، مجموعات، والمزيد",
          "welcomeText":
              "عند استكشاف خدمة مركز طول العمر قبل الاشتراك، قد يستخدم مركز طول العمر نشاط التصفح الخاص بك في علامة تبويب مركز طول العمر لتحسين الخدمة. بمجرد الاشتراك، يتم ربط بيانات التصفح والتدريبات بمعرف عشوائي. يمكن استخدام حسابك وحالة اشتراكك وتدريباتك لإرسال إشعارات لك",
          "seehowmanage": "انظر كيف يتم إدارة بياناتك",
          "agree": "أوافق",

          //menuScreen
          "user": "المستخدم",
          "healthInsights": "رؤى الصحة",
          "healthatoz": "الصحة من الألف إلى الياء",
          "wellness": "العافية",
          "subscription": "الاشتراك",
          "biometric": "القياسات الحيوية",
          "languages": "اللغات",
          "myorders": "طلباتي",
          "privecypolicy": "سياسة الخصوصية",
          "terms&condition": "الشروط والأحكام",
          "faqs": "الأسئلة الشائعة",
          "deletaccount": "حذف الحساب",
          "logout": "تسجيل الخروج",
          "confirmaccountdeletion": "تأكيد حذف الحساب",
          "areyousuredeleteaccount": "هل أنت متأكد أنك تريد حذف حسابك؟",
          "Cancel": " إلغاء ",
          "confirm": "تأكيد",

          // Terms and FAQ
          "termsandcondition": "الشروط والأحكام",
          "faq's": "الأسئلة الشائعة",
          "comingsoon": "قريباً",
          "selectLanguage": "اختر اللغة",

          // Subscription
          "validforlifetime": "صالح مدى الحياة",
          "until": "حتى",
          "basic": "أساسي",
          "yearsubscription": "اشتراك سنوي",
          "monthsubsricption": "اشتراك شهري",
          "daysubscription": "اشتراك يومي",
          "errorfetchingdata": "حدث خطأ أثناء جلب البيانات:",
          "subscriptionplan": "خطة الاشتراك",
          "unlockyourfullpotiential":
              "افتح إمكانياتك الكاملة مع خطط الاشتراك الخاصة بنا",
          "nosubscriptionplan": "لا توجد خطط اشتراك متاحة",
          "subscribe": "اشترك",
          "nofeaturesfound": "لم يتم العثور على ميزات",
          "unsubscribe": "إلغاء الاشتراك",

          // Wellness
          "discoverwellness": "اكتشف العافية",
          "becomeyourbestself":
              "كن أفضل نسخة من نفسك من خلال احتضان الجمال الطبيعي،\nتناول الطعام المغذي، نمط حياة نشيط، وعلاقات قوية",
          "healthaz": "الصحة من الألف إلى الياء",
          "becomeyourlifestyle":
              "كن أفضل نسخة من نفسك من خلال الجمال الطبيعي، التغذية الصحية، نمط حياة نشيط، والعلاقات الهادفة.",
          "catagories": "الفئات",
          "viewMore": "عرض المزيد",

          // Health Insights
          "todayworkout": "تمرين اليوم",
          "heartRate": "معدل ضربات القلب",
          "steps": "الخطوات",
          "water": "الماء",
          "glasses": "أكواب",
          "sleeping": "النوم",
          "hours": "ساعات",
          "earn": "احصل على",
          "badges": "الشارات",
          "connectwearable": "اتصل بالجهاز القابل للارتداء",
          "setworkoutgoal": "حدد هدف التمرين",
          "activitystats": "إحصاءات النشاط",
          "setGoal": "حدد الهدف",
          "calories": "السعرات الحرارية",
          "KCal": "كيلوكالوري",
          "timespend": "الوقت المنقضي",
          "sun": "الأحد",
          "mon": "الإثنين",
          "tue": "الثلاثاء",
          "wed": "الأربعاء",
          "thu": "الخميس",
          "fri": "الجمعة",
          "sat": "السبت",
          "summary": "الملخص",
          "overallprogress": "التقدم العام",
          "mealGuide": "دليل الوجبات",
          "breakfast": "الإفطار",
          "lunch": "الغداء",
          "dinner": "العشاء",
          "myprogram": "برنامجي",
          "overheadextension": "تمديدات العارضة العلوية",
          "minutesleft": "الدقائق المتبقية",
          "workoutdetail": "تفاصيل التمرين",
          "seeall": "عرض الكل",
          "day": "يوم",
          "selectany5": "اختر أي 5 تمارين",
          "legpressMachine": "آلة ضغط الأرجل",
          "minutes": "دقائق",
          "Each": "لكل",
          "workout": "التمرين",
          "daily": "يومي",
          "weekly": "أسبوعي",
          "monthly": "شهري",
          "Minutes": "دقائق",
          "exercise": "التمرين",
          "your": "الخاص بك",
          "KCAL": "كيلوكالوري",
          "bodytemp": "درجة حرارة\nالجسم",
          "normal": "طبيعي",
          "editWorkout": "تعديل التمرين",
          "finish": "إنهاء",
          "SUN": "الأحد",
          "MON": "الإثنين",
          "TUE": "الثلاثاء",
          "WED": "الأربعاء",
          "THU": "الخميس",
          "FRI": "الجمعة",
          "SAT": "السبت",
          "caloriesburnt": "السعرات الحرارية المحترقة",
          "Caloriesleft": "السعرات الحرارية المتبقية",
          "1stweek": "الأسبوع الأول",
          "workoutreport": "تقرير التمرين",
          "average": "المعدل:",
          "2ndweek": "الأسبوع الثاني",
          "3rdweek": "الأسبوع الثالث",
          "4thweek": "الأسبوع الرابع",
          "5thweek": "الأسبوع الخامس",
          "history": "التاريخ",
          "heartbpms": "نبضات القلب في الدقيقة",
          "bpmrange": "نطاق النبضات",
          "resting": "الراحة",
          "hightoday": "الأعلى اليوم",
          "lowtoday": "الأدنى اليوم",
          "bloodpressure": "ضغط الدم",
          "values": 'القيم',
          "condition": "الحالة",
          "date/time": "التاريخ/الوقت",
          "High": "عالي",
          "setmovegoal": "حدد هدف التحرك",
          "yourdailymovegoal": "هدف التحرك اليومي\nالخاص بك",
          "setactivegoal":
              "حدد هدفًا بناءً على نشاطك اليومي، أو حسب ما\n          تود أن تكون عليه",
          "kilocalperday": "كيلوكالوري/اليوم",
          "stepscount": "عدد الخطوات",
          "walking": "المشي",
          "distance": "المسافة",
          "running": "الركض",
          "editgoal": "تعديل الهدف",
          "totalsteps": "إجمالي الخطوات",
          "avgsteps": "متوسط الخطوات",
          "stepsreport": "تقرير الخطوات",
          "today": "اليوم",
          "hi": "مرحبًا",
          "oop": "عذرًا!",
          "hasnotachieve": "لم تحقق هدفك اليوم",
          "successisnotfinal":
              "النجاح ليس نهائيًا، والفشل ليس قاتلًا،\nإنها الشجاعة لمواصلة المحاولة",
          "tryagain": "حاول مرة أخرى",
          "pleaseselectactivity": "يرجى اختيار نشاط أولاً!",
          "inprogress": "قيد التقدم!",
          "almostdone": "على وشك الانتهاء!",
          "completed": "اكتمل!",
          "goodjob": "عمل جيد!",
          "yourdailytask": "مهامك اليومية",
          "+addactivity": "+ إضافة نشاط",
          "glassofwater": " كوب ماء",
          "glassesofWater": " أكواب ماء",
          "noactivityfound": "لم يتم العثور على نشاط، يرجى إضافة نشاط أولاً",
          "glass": "كوب",
          "totalIntake": "إجمالي المدخول",
          "pending": "قيد الانتظار",
          "healthySleep": "نوم صحي",
          "sleeptime": "وقت النوم",
          "thisweek": "هذا الأسبوع",
          "Hours": "ساعات",
          "perday": "في اليوم",
          "quality": "الجودة",
          "lastsleepinfo": "آخر معلومات النوم",
          "timeinsleep": "وقت النوم",
          "wakeuptime": "وقت الاستيقاظ",
          "wenttobed": "ذهب إلى السرير",
          "fellasleep": "غفى",
          "bedtime": "وقت النوم",
          "alarm": "المنبه",
          "setbedtime": "حدد وقت النوم",
          "bedTime": "وقت النوم",
          "wake_uptime": "وقت الاستيقاظ",
          "setAlarm": "ضبط المنبه",
          "time": "الوقت",
          "rewards": "المكافآت",
          "Sleeping": "النوم",
          "Rewards": "المكافآت",
          "Steps": "الخطوات",
          "WOrkout": "التمرين",
          "waterIntake": "تناول الماء",
          "addcategory": "إضافة فئة",
          "selectcategory": "اختر فئة",
          "pleaseselectcategory": "يرجى اختيار فئة",
          "pleaseenterquantityofglass": "يرجى إدخال كمية الأكواب",
          "quantityofGlass": "كمية الأكواب",
          "save": "حفظ",
          //Profile
          "profile": "الملف الشخصي",
          "basicmember": "عضو أساسي",
          "weight": "الوزن",
          "height": "الطول",
          "year": "السنة",
          "age": "العمر",
          "category": "الفئة",
          "justforyou": "فقط لأجلك",
          "befree": "كن حراً",
          "mInutes": "دقيقة",
          //EditProfile
          "editprofile": "تعديل الملف الشخصي",
          "pleaseenterusername": "يرجى إدخال اسم المستخدم",
          "fullname": "الاسم الكامل",
          "pleaseenterphone": "يرجى إدخال رقم الهاتف",
          "phoneshouldcontaindigits": "يجب أن يحتوي رقم الهاتف على أرقام فقط",
          "pleaseenteraddress": "يرجى إدخال عنوان البريد الإلكتروني",
          "emailAddress": "عنوان البريد الإلكتروني",
          "pleaseenterweight": "يرجى إدخال الوزن",
          "pleaseenterheight": "يرجى إدخال الطول",
          "gender": "الجنس",
          "disease": "الأمراض",
          "activitylevel": "مستوى النشاط",
          "update": "تحديث",
          "choosephoto": "اختر صورة الملف الشخصي",
          "camera": "الكاميرا",
          "gallery": "المعرض",
          //Notification
          "yesterday": "أمس",
          "previous": "سابق",
          "nonotificationyet": "لا توجد إشعارات بعد",
          "notificationactivity": "ستظهر الإشعارات حول نشاطك",
          "shopuphere": "هنا",
          "selectdiseases": "اختر الأمراض",
          "notification": "إشعار",
          //home
          "fityoungmandoing":
              "شاب لياقته جيدة يقوم بتمارين\nتمدد باستخدام الحبل",
          "startexercise": "ابدأ التمرين",
          "whatareyoulookingfor": "ماذا تبحث عنه؟",
          "improvelife": "حسّن نمط حياتك\n",
          "gym": "صالة رياضية",
          "choosegym": "اختيار الصالة الرياضية\nالمناسبة لك",
          "shopOnline": "تسوق عبر الإنترنت",
          "gymandmore": "أدوات صالة رياضية، تغذية،\nمكملات، وأكثر!",
          "trackheart": "تتبع معدل ضربات القلب،\nالتمارين، وأكثر!",
          "nutrition": "تغذية",
          "balancediet": "أهمية النظام الغذائي المتوازن",
          "community": "مجتمع",
          "center": "مركز",
          "schedule": "الجدول الزمني",
          "home": "الرئيسية",
          // SelectGymScreen
          "SelectGym": "اختر النادي",
          'SelectGymScreenText': "استعد لياقتك مع\nأعضائنا في النادي الرياضي",
          'NoGymAvailable': "لا توجد نوادي متاحة.",
          'SubscribeToPremium': 'اشترك في الباقة المميزة',
          'SelectGymScreenText2':
              'استمتع بالوصول غير المحدود إلى محتوياتنا المميزة',
          "selectgym": "اختر النادي",
// TrainersScreen
          "FitnessTrainer": "مدرب اللياقة",
          "NoTrainersAvailableForThisGym.":
              "لا يوجد مدربين متاحين لهذا النادي.",
          "years": "سنوات",
          "Online": "أونلاين",
          "activeClients": "العملاء النشطين",
          "HaveMadeAnAppointment": "حددوا موعدًا",
          "beginTraining": "ابدأ التدريب",
// TrainersInfoScreen
          'HighIntensityTraining': "تدريب عالي الكثافة",
          "Reviews": "المراجعات",
          "BeginTraining": "ابدأ التدريب",
          "ReadAllReviews": "اقرأ جميع المراجعات",
          "NoReviewsAvailable": "لا توجد مراجعات متاحة",
          "Experience": "الخبرة",
          "Completed": "مكتمل",
          "ActiveClients": "العملاء النشطين",
// GymExerciseScreen
          "NoVideoFoundAgainstthisCategory":
              "لم يتم العثور على فيديو لهذه الفئة",
          "Exercise": "التمرين",
          "16ActiveClients": "16 عميل نشط",
// "HaveMadeAnAppointment": "حددوا موعدًا",
          "AvailableTimings": "الأوقات المتاحة",
          "09:00 am": "09:00 صباحًا",
          "05:00 pm": "05:00 مساءً",
// TrainerAppointmentScreen
          "Appointment": "الموعد",
          "SelectDate": "اختر التاريخ",
          "SelectTime": "اختر الوقت",
          "Appointment Notes": "ملاحظات الموعد",
          "PayOnline": "ادفع أونلاين",
// TrainerReviewsScreen
          "Ratings": "التقييمات",
          "WriteAReview": "اكتب مراجعة",
          "review(optional)": "المراجعة (اختياري)",
          "send": "إرسال",
          "rating": "التقييم",
// WorkOutDetailScreen
          "MyExercises": "تماريني",
          "ExerciseDescriptionGoesHere.": "وصف التمرين يظهر هنا.",
          "Done": "تم",
          "FailedToLoadVideo": "فشل تحميل الفيديو",
          "pleasecompleteprevious": "يرجى إكمال التكرارات السابقة أولاً",

//changepassword
          "changePass": "تغيير كلمة المرور",
          "enteroldPass": "أدخل كلمة المرور القديمة",
          "passresetfailed": "فشل إعادة تعيين كلمة المرور",

//custompopup
          "attention": "انتبه!",
          "updatepackage": "تحديث الباقة",
          //community
          "createCommunity": "إنشاء مجتمع",
          "connectwithcommunity": "التواصل مع المجتمع",
          "selectyourcommunity": "اختر مجتمعك",
          "communitypermission": "أذونات المجتمع",
          "approvenewmember": "الموافقة على أعضاء جدد",
          "sendmessage&activity": "إرسال رسائل وأنشطة",
          "addothermembers": "إضافة أعضاء آخرين",
          "addmembers": "إضافة أعضاء",
          "searchid": "البحث عن معرف",
          "joingroup": "الانضمام إلى المجموعة",
          "chat": "دردشة",
          "members": "الأعضاء",
          "searchanyrecipe": "ابحث عن أي وصفات",
          "upcomingevents": "الأحداث القادمة",
          //shoponline
          "searchhere": "ابحث هنا",
          "color": "اللون",
          "addtocart": "أضف إلى السلة",
          "mycart": "سلتي",
          "myOrders": "طلباتي",
          "itemTotal": "إجمالي العناصر",
          "selectbadge": "اختر الشارة",
          "discount": "خصم",
          "deliveryfee": "رسوم التوصيل",
          "grandtotal": "الإجمالي الكلي",
          "ordernow": "اطلب الآن",
          "orderId": "رقم الطلب:",
          "orderDate": "تاريخ ووقت الطلب:",
          "qty": "الكمية:",
          "delivered": "تم التوصيل",
          "viewDetails": "عرض التفاصيل",
          "reorder": "إعادة الطلب",
          "placed": "تم الطلب",
          "cancelled": "ألغيت",
          "orderdetails": "تفاصيل الطلب",
          "cancelOrder": "إلغاء الطلب",
          "return": "إرجاع",
          "deliveryAddress": "عنوان التوصيل",
          "orderSummary": "ملخص الطلب",
          "viewInvoice": "عرض الفاتورة",
          "favourite": "المفضلة",
          "Addtocart": "أضف إلى السلة",
          "shippingaddress": "عنوان الشحن",
          "address": "العنوان",
          "Summary": "الملخص",
          "payment": "الدفع",
          "addnewaddress": "+ أضف عنوان جديد",
          "paynow": "ادفع الآن",
          "yourpaymentdone": "تم الدفع بنجاح",
          "thankyouforshopping": "شكراً لتسوقك معنا",
          "seeorderDetails": "عرض تفاصيل الطلب",
          "continueshopping": "استمر بالتسوق",
          //Schedule
          "myAppointments": "مواعيدي",
          "upcoming": "القادمة",
          "cOmpleted": "مكتمل",
          "bookingid": "معرف الحجز:",
          "booked": "محجوز",
          "onlineConsultation": "استشارة عبر الإنترنت",
          "reschedule": "إعادة جدولة",
          "bookanAppointment": "احجز موعدًا",
          "selectExpert": "اختر الخبير",
          "online": "عبر الإنترنت",
          "havemadeappointment": "تم تحديد موعد",
          "availabletimings": "الأوقات المتاحة",
          "bookAppointment": "احجز موعدًا",
          "bookNow": "احجز الآن",
          "selectDate": "اختر التاريخ",
          "selectTime": "اختر الوقت",
          "appointmentNotes": "ملاحظات الموعد",
          "experiance": "الخبرة",
          "readallReviews": "اقرأ جميع المراجعات",
          "reviews": "المراجعات",
          "ratings": "التقييمات",
          "writeareview": "اكتب مراجعة",
          "yoursessionwith": "جلستك مع",
          "iscompleted": "اكتملت! 🎉",
          "welovetohere": "نود أن نسمع منك",
          "feedback": "التعليقات",
          "writeyourfeedback": "اكتب ملاحظاتك هنا",
          "skip&godashboard": "تخطي وانتقل إلى لوحة القيادة"
        },
        "ur_PK": {
          "WelcomeTo": "خوش آمدید",
          "Longevity": "لونگیویٹی",
          "Hub": "حب",
          "WelcomeScreen1text":
              "پہلی فٹنس ایپ، اپنی فٹنس کو بہتر بنائیں، ذہنی سکون کا مشق کریں، یا خاص طور پر تیار کیے گئے ورزشوں اور مراقبہ کے سلسلے کے ساتھ نئی مہمات کے لیے تیار ہوں۔",
          "GeStarted": "شروع کریں",
          "WhereverYouAre": "جہاں کہیں بھی آپ ہیں",
          "Health": "صحت",
          "is": "ہے",
          "NumberOne": "نمبر ایک",
          "Workout": "ورزش",
          "Categories": "زمرے",
          "BeginYour": "اپنی",
          "Transformation": "تبدیلی شروع کریں",
          "NewEra": "نیا دور",
          "of": "کا",
          "Wellbeing": "فلاح و بہبود",
          "WelcomeScreen2text":
              "بالکل معلوم کریں کہ کون سی غذا اور تربیت آپ کے لیے خاص طور پر کارآمد ہوگی۔",
          "WelcomeScreen3text":
              "ورزش کے زمرے آپ کو طاقت حاصل کرنے، بہتر شکل میں آنے اور صحت مند طرز زندگی کو اپنانے میں مدد دیں گے۔",
          "WelcomeScreen4text":
              "ہمارا اے آئی آپ کے صحت کے ڈیٹا کا تجزیہ کرتا ہے تاکہ ذاتی نوعیت کے کھانے کے منصوبے تجویز کرے۔",
          "WelcomeScreen5text":
              "آپ کی انگلیوں پر فلاح و بہبود، گہرے انائٹس، بہتر صحت، آپ کے لیے متناسب غذائیت، سمجھداری سے حرکت کریں، بہتر زندگی گزاریں، کیا آپ تیار ہیں؟",
          "skip": "چھوڑ دیں",
          "WelcomeBack": "خوش آمدید",
          "ForgotPassword?": "پاسورڈ بھول گئے؟",
          "ForgotPassword": "پاسورڈ بھول گئے",
          "SignIn": "سائن ان کریں",
          "SignInWith": "کے ساتھ سائن ان کریں",
          "signup": "سائن اپ",
          "DontHaveAnAccount?": "اکاؤنٹ نہیں ہے؟",
          "ForgetPasswordScreenText":
              "یہ ہو جاتا ہے، براہ کرم اپنے اکاؤنٹ سے وابستہ ای میل درج کریں۔",
          "pleaseenteremail": "براہ کرم ای میل درج کریں",
          "emailaddress": "ای میل پتہ",
          "submit": "جمع کرائیں",
          "cancel": "منسوخ کریں",
          "NeedHelp?VisitOur": "مدد چاہیے؟ ہمارا وزٹ کریں",
          "HelpCenter": "ہیلپ سینٹر",
          "Email": "ای میل",
          "EnterEmail": "ای میل درج کریں",
          "EnterPassword": "پاسورڈ درج کریں",
          "Password": "پاسورڈ",

          // Otp Screen
          "enterotp": "او ٹی پی درج کریں",
          "thankyou": "شکریہ!",
          "otpsendtoyouremail":
              "ایک او ٹی پی آپ کے ای میل پتہ پر بھیج دیا گیا ہے",
          "expiresin": "ختم ہو جائے گا",
          "resend": "دوبارہ بھیجیں",
          "otpfailed": "او ٹی پی کی تصدیق ناکام ہوگئی",

          //createNewPasswordScreen
          "createnewpass": "نیا پاسورڈ بنائیں",
          "kindlyenteruniquePass": "براہ کرم ایک منفرد پاسورڈ درج کریں",
          "enterPass": "پاسورڈ درج کریں",
          "passMustbe6characterlong": "پاسورڈ کم از کم 6 حروف طویل ہونا چاہیے",
          "mustContainUppercaseletter":
              "پاسورڈ میں کم از کم ایک بڑا حرف ہونا چاہیے",
          "mustcontainOneNumber": "پاسورڈ میں کم از کم ایک نمبر ہونا چاہیے",
          "mustcontainSpecialChar":
              "پاسورڈ میں کم از کم ایک خاص حرف ہونا چاہیے",
          "newPass": "نیا پاسورڈ",
          "confirmnewPass": "نیا پاسورڈ کی تصدیق کریں",
          "passresetFailed": "پاسورڈ ری سیٹ ناکام ہوگیا",

          //passsuccessScreen
          "youwillberedirectedin5":
              "آپ کو 5 سیکنڈ میں لاگ ان صفحہ پر بھیج دیا جائے گا...",
          "click": "کلک کریں",
          "Here": "یہاں",
          "ifYounotredirect": "اگر آپ خود بخود نہیں بھیجے جا رہے ہیں",

          //SignupScreen
          "enteruserName": "صارف کا نام درج کریں",
          "shouldOnlycontainAlphabets":
              "صارف کا نام صرف حروف پر مشتمل ہونا چاہیے",
          "name": "نام",
          "enterPhone": "فون نمبر درج کریں",
          "shouldonlyContainDigits": "فون نمبر میں صرف ہندسے ہونے چاہئیں",
          "phone": "فون",
          "enterEmail": "ای میل درج کریں",
          "invalidEmailFormat": "غلط ای میل فارمیٹ",
          "email": "ای میل",
          "password": "پاسورڈ",
          "enterconfirmPass": "تصدیق شدہ پاسورڈ درج کریں",
          "confirmPass": "تصدیق شدہ پاسورڈ",
          "orRegisterWith": "یا اس کے ساتھ رجسٹر کریں",
          "alreadyhaveanAccount": "پہلے سے ہی اکاؤنٹ موجود ہے؟",
          "login": "لاگ ان کریں!",

          //stepsScreen
          //genderScreen
          "step1of7": "مرحلہ 1 از 7",
          "tellusaboutyourself": "اپنے بارے میں ہمیں بتائیں!",
          "toGiveYoubetterexperiance":
              "آپ کو بہتر تجربہ دینے کے لیے ہمیں آپ کی جنس کا پتہ ہونا ضروری ہے۔",
          "male": "مرد",
          "female": "خاتون",
          "next": "اگلا",

          //ageScreen
          "step2of7": "مرحلہ 2 از 7",
          "howoldareyou": "آپ کی عمر کتنی ہے؟",
          "thishelpuscreateplan":
              "یہ ہمیں آپ کے ذاتی نوعیت کا منصوبہ بنانے میں مدد دیتا ہے۔",
          "jan": "جنوری",
          "feb": "فروری",
          "mar": "مارچ",
          "apr": "اپریل",
          "may": "مئی",
          "jun": "جون",
          "jul": "جولائی",
          "aug": "اگست",
          "sep": "ستمبر",
          "oct": "اکتوبر",
          "nov": "نومبر",
          "dec": "دسمبر",

          //heightScreen
          "step3of7": "مرحلہ 3 از 7",
          "selectHeight": "قد منتخب کریں",
          "thishelpcreateyourplan":
              "یہ ہمیں آپ کے ذاتی نوعیت کا منصوبہ بنانے میں مدد دیتا ہے۔",
          "feet": "فٹ",

          //weightScreen
          "step4to7": "مرحلہ 4 از 7",
          "whatisyourweight": "آپ کا وزن کیا ہے؟",
          "youcanchangelater": "آپ اسے بعد میں ہمیشہ تبدیل کر سکتے ہیں۔",

          //physicalActivityLevel
          "step5of7": "مرحلہ 5 از 7",
          "yourphysicalActivitylevel":
              "آپ کی روزمرہ کی جسمانی سرگرمی کی سطح کیا ہے؟",

          //activitylevelScreen
          "step6of7": "مرحلہ 6 از 7",
          "chooseactivity": "سرگرمیاں منتخب کریں جو آپ کو پسند ہیں۔",
          "noactivityavailable": "کوئی سرگرمی دستیاب نہیں ہے۔",
          "pleaseselectoneactivity":
              "براہ کرم آگے بڑھنے کے لیے کم از کم ایک سرگرمی منتخب کریں۔",
          "warning": "انتباہ!",
          "ok": "اوکے",

          //selectdiseaseScreen
          "step7of7": "مرحلہ 7 از 7",
          "selectDisease": "بیماری کا انتخاب کریں",
          "search": "تلاش",
          //welcomeScreen
          "welcometolongevity": "خوش آمدید\nلانگ جیویٹی ہب",
          "workoutsforeveryone": "سب کے لئے ورک آؤٹس",
          "elevenDifferentTypesfromHiit":
              "ہائی آئی ٹی سے یوگا تک گیارہ مختلف اقسام",
          "guidedMeditation": "رہنمائی کی مراقبہ",
          "paracticemindfullnesin": "صرف 5 منٹ میں ذہن سازی کی مشق کریں",
          "programandmore": "پروگرام، مجموعے، اور مزید",
          "welcomeText":
              "جب آپ سبسکرپشن سے پہلے لانگ جیویٹی ہب سروس کو تلاش کرتے ہیں، تو لانگ جیویٹی ہب آپ کی براؤزنگ کی سرگرمی کو سروس کو بہتر بنانے کے لیے استعمال کر سکتا ہے۔ سبسکرپشن کرنے کے بعد، آپ کی براؤزنگ اور ورک آؤٹ ڈیٹا ایک بے ترتیب شناخت کنندہ کے ساتھ منسلک ہو جاتی ہے۔ آپ کا اکاؤنٹ، سبسکرپشن کی حالت، اور ورک آؤٹ آپ کو نوٹیفیکیشن بھیجنے کے لیے استعمال ہو سکتے ہیں۔",
          "seehowmanage": "دیکھیں کہ آپ کا ڈیٹا کیسے منظم ہوتا ہے۔",
          "agree": "متفق ہوں",

          //menuScreen
          "user": "صارف",
          "healthInsights": "صحت کی بصیرت",
          "healthatoz": "صحت A-Z",
          "wellness": "خوشحالی",
          "subscription": "سبسکرپشن",
          "biometric": "بایومیٹرک",
          "languages": "زبانیں",
          "myorders": "میرے آرڈرز",
          "privecypolicy": "رازداری کی پالیسی",
          "terms&condition": "شرائط و ضوابط",
          "faqs": "عمومی سوالات",
          "deletaccount": "اکاؤنٹ حذف کریں",
          "logout": "لاگ آؤٹ",

          "confirmaccountdeletion": "اکاؤنٹ حذف کرنے کی تصدیق کریں",
          "areyousuredeleteaccount":
              "کیا آپ واقعی اپنے اکاؤنٹ کو حذف کرنا چاہتے ہیں؟",
          "Cancel": " منسوخ کریں ",
          "confirm": "تصدیق کریں",
          "termsandcondition": "شرائط و ضوابط",
          "faq's": "عمومی سوالات",
          "comingsoon": "جلد آرہا ہے",
          "selectLanguage": "زبان منتخب کریں",
          //subscription
          "validforlifetime": "زندگی بھر کے لیے معتبر",
          "until": "تک",
          "basic": "بنیادی",
          "yearsubscription": "سالانہ سبسکرپشن",
          "monthsubsricption": "ماہانہ سبسکرپشن",
          "daysubscription": "دن سبسکرپشن",
          "errorfetchingdata": "ڈیٹا حاصل کرنے میں خرابی:",
          "subscriptionplan": "سبسکرپشن پلان",
          "unlockyourfullpotiential":
              "ہمارے سبسکرپشن پلانز کے ساتھ اپنی مکمل صلاحیت کو کھولیں",
          "nosubscriptionplan": "کوئی سبسکرپشن پلان دستیاب نہیں ہے۔",
          "subscribe": "سبسکرائب کریں",
          "nofeaturesfound": "کوئی خصوصیات دستیاب نہیں ہیں",
          "unsubscribe": "منسوخ کریں",
          //wellness
          "discoverwellness": "خوشحالی دریافت کریں",
          "becomeyourbestself":
              "قدرتی خوبصورتی، صحت مند غذا، فعال طرز زندگی، اور مضبوط تعلقات کو اپنا کر اپنے بہترین خود بنیں۔",
          "healthaz": "صحت A-Z",
          "becomeyourlifestyle":
              "قدرتی خوبصورتی، صحت مند غذا، فعال طرز زندگی، اور معنی خیز تعلقات کے ذریعے اپنے بہترین خود بنیں۔",
          "catagories": "زمریں",
          "viewMore": "مزید دیکھیں",
          //HealthInsights
          "todayworkout": "آج کی ورزش",
          "heartRate": "دل کی دھڑکن",
          "steps": "قدم",
          "water": "پانی",
          "glasses": "گلاس",
          "sleeping": "نیند",
          "hours": "گھنٹے",
          "earn": "کمائیں",
          "badges": "بیجز",
          "connectwearable": "ویئر ایبل جوڑیں",
          "setworkoutgoal": "ورک آؤٹ کا ہدف مقرر کریں",
          "activitystats": "سرگرمی کے اعدادوشمار",
          "setGoal": "ہدف مقرر کریں",
          "calories": "کیلوریز",
          "KCal": "کلوکیل",
          "timespend": "وقت گزاری",
          "sun": "اتوار",
          "mon": "پیر",
          "tue": "منگل",
          "wed": "بدھ",
          "thu": "جمعرات",
          "fri": "جمعہ",
          "sat": "ہفتہ",
          "summary": "خلاصہ",
          "overallprogress": "مجموعی ترقی",
          "mealGuide": "کھانے کی رہنمائی",
          "breakfast": "ناشتا",
          "lunch": "دوپہر کا کھانا",
          "dinner": "رات کا کھانا",
          "myprogram": "میرا پروگرام",
          "overheadextension": "اوور ہیڈ بار ایکسٹینشنز",
          "minutesleft": "بچے ہوئے منٹ",
          "workoutdetail": "ورک آؤٹ کی تفصیل",
          "seeall": "سب دیکھیں",
          "day": "دن",
          "selectany5": "کوئی بھی 5 ورزشیں منتخب کریں",
          "legpressMachine": "لیگ پریس مشین",
          "minutes": "منٹ",
          "Each": "ہر",
          "workout": "ورک آؤٹ",
          "daily": "روزانہ",
          "weekly": "ہفتہ وار",
          "monthly": "ماہانہ",
          "Minutes": "منٹ",
          "exercise": "ورزش",
          "your": "آپ کا",
          "KCAL": "کلوکیل",
          "bodytemp": "جسمانی درجہ حرارت",
          "normal": "معمول",
          "editWorkout": "ورک آؤٹ کو ایڈٹ کریں",
          "finish": "ختم کریں",
          "SUN": "اتوار",
          "MON": "پیر",
          "TUE": "منگل",
          "WED": "بدھ",
          "THU": "جمعرات",
          "FRI": "جمعہ",
          "SAT": "ہفتہ",
          "caloriesburnt": "جلائی گئی کیلوریز",
          "Caloriesleft": "بچی ہوئی کیلوریز",
          "1stweek": "پہلا ہفتہ",
          "workoutreport": "ورک آؤٹ کی رپورٹ",
          "average": "اوسط:",
          "2ndweek": "دوسرا ہفتہ",
          "3rdweek": "تیسرا ہفتہ",
          "4thweek": "چوتھا ہفتہ",
          "5thweek": "پانچواں ہفتہ",
          "history": "تاریخ",
          "heartbpms": "دل کی دھڑکن کے بی پی ایم",
          "bpmrange": "بی پی ایم رینج",
          "resting": "آرام",
          "hightoday": "آج کا زیادہ",
          "lowtoday": "آج کا کم",
          "bloodpressure": "خون کا دباؤ",
          "values": "قدریں",
          "condition": "حالت",
          "date/time": "تاریخ/وقت",
          "High": "زیادہ",
          "setmovegoal": "موو کا ہدف مقرر کریں",
          "yourdailymovegoal": "آپ کا روزانہ موو کا ہدف",
          "setactivegoal":
              "ایک ایسا ہدف مقرر کریں جو آپ کی روزانہ کی سرگرمی پر مبنی ہو یا آپ کتنے فعال ہونا چاہتے ہیں۔",
          "kilocalperday": "کلو کیلوریز/دن",
          "stepscount": "قدموں کی تعداد",
          "walking": "چلنا",
          "distance": "فاصلہ",
          "running": "دوڑنا",
          "editgoal": "ہدف ایڈٹ کریں",
          "totalsteps": "کل قدم",
          "avgsteps": "اوسط قدم",
          "stepsreport": "قدموں کی رپورٹ",
          "today": "آج",
          "hi": "ہیلو",
          "oop": "اوپ!",
          "hasnotachieve": "آج آپ کا ہدف مکمل نہیں ہوا",
          "successisnotfinal":
              "کامیابی آخری نہیں ہے، ناکامی مہلک نہیں ہے: یہ ہمت ہے جو اہمیت رکھتی ہے۔",
          "tryagain": "دوبارہ کوشش کریں",
          "pleaseselectactivity": "براہ کرم پہلے سرگرمی منتخب کریں!",
          "inprogress": "جاری ہے!",
          "almostdone": "تقریباً مکمل!",
          "completed": "مکمل!",
          "goodjob": "اچھا کام!",
          "yourdailytask": "آپ کے روزانہ کے کام",
          "+addactivity": "+ سرگرمی شامل کریں",
          "glassofwater": "پانی کا گلاس",
          "glassesofWater": "پانی کے گلاس",
          "noactivityfound": "کوئی سرگرمی نہیں ملی، پہلے سرگرمی شامل کریں",
          "glass": "گلاس",
          "totalIntake": "کل انٹیک",
          "pending": "زیر التواء",
          "healthySleep": "صحت مند نیند",
          "sleeptime": "نیند کا وقت",
          "thisweek": "اس ہفتے",
          "Hours": "گھنٹے",
          "perday": "فی دن",
          "quality": "معیار",
          "lastsleepinfo": "آخری نیند کی معلومات",
          "timeinsleep": "نیند میں وقت",
          "wakeuptime": "جاگنے کا وقت",
          "wenttobed": "بستر پر گیا",
          "fellasleep": "سو گیا",
          "bedtime": "سونے کا وقت",
          "alarm": "الارم",
          "setbedtime": "سونے کا وقت مقرر کریں",
          "bedTime": "سونے کا وقت",
          "wake_uptime": "جاگنے کا وقت",
          "setAlarm": "الارم مقرر کریں",
          "time": "وقت",
          "rewards": "انعامات",
          "Sleeping": "نیند",
          "Rewards": "انعامات",
          "Steps": "قدم",
          "WOrkout": "ورک آؤٹ",
          "waterIntake": "پانی کا انٹیک",
          "addcategory": "کیٹیگری شامل کریں",
          "selectcategory": "کیٹیگری منتخب کریں",
          "pleaseselectcategory": "براہ کرم ایک کیٹیگری منتخب کریں",
          "pleaseenterquantityofglass": "براہ کرم گلاس کی مقدار درج کریں",
          "quantityofGlass": "گلاس کی مقدار",
          "save": "محفوظ کریں",
          //Profile
          "profile": "پروفائل",
          "basicmember": "بنیادی رکن",
          "weight": "وزن",
          "height": "قد",
          "year": "سال",
          "age": "عمر",
          "category": "کیٹیگری",
          "justforyou": "آپ کے لئے خاص",
          "befree": "آزاد رہیں",
          "mInutes": "منٹ",
          //EditProfile
          "editprofile": "پروفائل ایڈٹ کریں",
          "pleaseenterusername": "براہ کرم صارف نام درج کریں",
          "fullname": "پورا نام",
          "pleaseenterphone": "براہ کرم فون نمبر درج کریں",
          "phoneshouldcontaindigits":
              "فون نمبر میں صرف ہندسوں کا ہونا ضروری ہے",
          "pleaseenteraddress": "براہ کرم ای میل پتہ درج کریں",
          "emailAddress": "ای میل پتہ",
          "pleaseenterweight": "براہ کرم وزن درج کریں",
          "pleaseenterheight": "براہ کرم قد درج کریں",
          "gender": "جنس",
          "disease": "امراض",
          "activitylevel": "سرگرمی کی سطح",
          "update": "اپ ڈیٹ کریں",
          "choosephoto": "پروفائل تصویر منتخب کریں",
          "camera": "کیمرہ",
          "gallery": "گیلری",
          "selectdiseases": "امراض منتخب کریں",
          //Notification
          "yesterday": "کل",
          "previous": "پچھلا",
          "nonotificationyet": "ابھی کوئی اطلاع نہیں",
          "notificationactivity":
              "آپ کی سرگرمی سے متعلق اطلاعات یہاں دکھائی جائیں گی۔",
          "shopuphere": "یہاں دکھائی جائیں گے.",
          "notification": "اطلاع",
          //home
          "fityoungmandoing": "فٹ جوان آدمی بیٹل اسٹریچ ٹریننگ کر رہا ہے",
          "startexercise": "ورزش شروع کریں",
          "whatareyoulookingfor": "آپ کیا تلاش کر رہے ہیں؟",
          "improvelife": "اپنی زندگی کو بہتر بنائیں",
          "gym": "جم",
          "choosegym": "آپ کے لیے صحیح جم کا انتخاب",
          "shopOnline": "آن لائن خریداری",
          "gymandmore": "جم گیجٹس، غذائیت، سپلیمنٹس اور مزید!",
          "trackheart": "دل کی دھڑکن، ورزش اور مزید کو ٹریک کریں!",
          "nutrition": "غذا",
          "balancediet": "متوازن غذا کی اہمیت",
          "community": "برادری",
          "center": "سنٹر",
          "schedule": "شیڈول",
          "home": "گھر",
          // SelectGymScreen
          "SelectGym": "جم منتخب کریں",
          "SelectGymScreenText":
              "اپنی فٹنس کو ٹریک پر واپس لائیں ہمارے جم ممبروں کے ساتھ",
          "NoGymAvailable": "کوئی جم دستیاب نہیں",
          "SubscribeToPremium": "پریمیم سبسکرائب کریں",
          "SelectGymScreenText2":
              "ہمارے پریمیم مواد تک لامحدود رسائی حاصل کریں",
          "selectgym": "جم منتخب کریں",
          // TrainersScreen
          "FitnessTrainer": "فٹنس ٹرینر",
          "NoTrainersAvailableForThisGym.":
              "اس جم کے لئے کوئی ٹرینر دستیاب نہیں ہے۔",
          "years": "سال",
          "Online": "آن لائن",
          "activeClients": "فعال کلائنٹس",
          "HaveMadeAnAppointment": "نے ملاقات کا وقت مقرر کیا ہے",
          "beginTraining": "تربیت شروع کریں",
          // TrainersInfoScreen
          "HighIntensityTraining": "اعلی شدت کی تربیت",
          "Reviews": "جائزے",
          "BeginTraining": "تربیت شروع کریں",
          "ReadAllReviews": "تمام جائزے پڑھیں",
          "NoReviewsAvailable": "کوئی جائزے دستیاب نہیں",
          "Experience": "تجربہ",
          "Completed": "مکمل",
          "ActiveClients": "فعال کلائنٹس",
          // GymExerciseScreen
          "NoVideoFoundAgainstthisCategory":
              "اس زمرے کے خلاف کوئی ویڈیو نہیں ملی",
          "Exercise": "ورزش",
          "16ActiveClients": "16 فعال کلائنٹس",
          "AvailableTimings": "دستیاب اوقات",
          "09:00 am": "09:00 صبح",
          "05:00 pm": "05:00 شام",
          // TrainerAppointmentScreen
          "Appointment": "ملاقات",
          "SelectDate": "تاریخ منتخب کریں",
          "SelectTime": "وقت منتخب کریں",
          "Appointment Notes": "ملاقات کی نوٹس",
          "PayOnline": "آن لائن ادائیگی کریں",
          // TrainerReviewsScreen
          "Ratings": "ریٹنگز",
          "WriteAReview": "جائزہ لکھیں",
          "review(optional)": "جائزہ (اختیاری)",
          "send": "ارسال کریں",
          "rating": "ریٹنگ",
          // WorkOutDetailScreen
          "MyExercises": "میری ورزشیں",
          "ExerciseDescriptionGoesHere.": "ورزش کی تفصیل یہاں آئے گی۔",
          "Done": "مکمل",
          "FailedToLoadVideo": "ویڈیو لوڈ کرنے میں ناکامی",
          "pleasecompleteprevious": "براہ کرم پہلے کی باریاں مکمل کریں",

          // changepassword
          "changePass": "پاسورڈ تبدیل کریں",
          "enteroldPass": "پرانا پاسورڈ درج کریں",
          "passresetfailed": "پاسورڈ دوبارہ ترتیب دینے میں ناکامی",

          // custompopup
          "attention": "توجہ!",
          "updatepackage": "پیکیج کو اپ ڈیٹ کریں",

          // community
          "createCommunity": "کمیونٹی بنائیں",
          "connectwithcommunity": "کمیونٹی سے جڑیں",
          "selectyourcommunity": "اپنی کمیونٹی منتخب کریں",
          "communitypermission": "کمیونٹی کی اجازتیں",
          "approvenewmember": "نئے اراکین کی منظوری دیں",
          "sendmessage&activity": "پیغامات اور سرگرمیاں بھیجیں",
          "addothermembers": "دیگر اراکین شامل کریں",
          "addmembers": "اراکین شامل کریں",
          "searchid": "ID تلاش کریں",
          "joingroup": "گروپ میں شامل ہوں",
          "chat": "چیٹ",
          "members": "اراکین",
          "searchanyrecipe": "کسی بھی نسخے کی تلاش کریں",
          "upcomingevents": "آنے والے واقعات",
          // shoponline
          "searchhere": "یہاں تلاش کریں",
          "color": "رنگ",
          "addtocart": "کارٹ میں شامل کریں",
          "mycart": "میرا کارٹ",
          "myOrders": "میرے آرڈرز",
          "itemTotal": "آئٹم کل",
          "selectbadge": "بیج منتخب کریں",
          "discount": "چھوٹ",
          "deliveryfee": "ڈلیوری فیس",
          "grandtotal": "مجموعی کل",
          "ordernow": "ابھی آرڈر کریں",
          "orderId": "آرڈر آئی ڈی:",
          "orderDate": "آرڈر کی تاریخ اور وقت:",
          "qty": "مقدار:",
          "delivered": "ترسیل ہو گئی",
          "viewDetails": "تفصیلات دیکھیں",
          "reorder": "دوبارہ آرڈر کریں",
          "placed": "موجود",
          "cancelled": "منسوخ",
          "orderdetails": "آرڈر کی تفصیلات",
          "cancelOrder": "آرڈر منسوخ کریں",
          "return": "واپسی",
          "deliveryAddress": "ڈلیوری کا پتہ",
          "orderSummary": "آرڈر کا خلاصہ",
          "viewInvoice": "انوائس دیکھیں",
          "favourite": "پسندیدہ",
          "Addtocart": "کارڈ میں شامل کریں",
          "shippingaddress": "شپنگ ایڈریس",
          "address": "پتہ",
          "Summary": "خلاصہ",
          "payment": "ادائیگی",
          "addnewaddress": "+ نیا پتہ شامل کریں",
          "paynow": "ابھی ادائیگی کریں",
          "yourpaymentdone": "آپ کی ادائیگی کامیابی کے ساتھ مکمل ہو گئی ہے۔",
          "thankyouforshopping": "ہم سے خریداری کرنے کا شکریہ",
          "seeorderDetails": "آرڈر کی تفصیلات دیکھیں",
          "continueshopping": "خریداری جاری رکھیں",

          // Schedule
          "myAppointments": "میرے اپائنٹمنٹس",
          "upcoming": "آنے والے",
          "cOmpleted": "مکمل شدہ",
          "bookingid": "بکنگ آئی ڈی:",
          "booked": "بک کیا گیا",
          "onlineConsultation": "آن لائن مشاورت",
          "reschedule": "دوبارہ شیڈول کریں",
          "bookanAppointment": "اپائنٹمنٹ بک کریں",
          "selectExpert": "ماہر منتخب کریں",
          "online": "آن لائن",
          "havemadeappointment": "نے ملاقات کا وقت مقرر کیا ہے",
          "availabletimings": "دستیاب اوقات",
          "bookAppointment": "اپائنٹمنٹ بک کریں",
          "bookNow": "ابھی بک کریں",
          "selectDate": "تاریخ منتخب کریں",
          "selectTime": "وقت منتخب کریں",
          "appointmentNotes": "ملاقات کی نوٹس",
          "experiance": "تجربہ",
          "readallReviews": "تمام جائزے پڑھیں",
          "reviews": "جائزے",
          "ratings": "ریٹنگز",
          "writeareview": "جائزہ لکھیں",
          "yoursessionwith": "آپ کا سیشن",
          "iscompleted": "مکمل ہو گیا! 🎉",
          "welovetohere": "ہم آپ کی رائے سننا پسند کریں گے",
          "feedback": "آراء",
          "writeyourfeedback": "اپنی رائے یہاں لکھیں",
          "skip&godashboard": "چھوڑیں اور ڈیش بورڈ پر جائیں"
        }
      };
}
